-- Restaurant menu seed data, generated from the local dev database.
-- Safe to run more than once: every INSERT is ON DUPLICATE KEY UPDATE, keyed on id.
-- Run against the live database with:
--   mysql -u <user> -p <database> < seed-restaurant-menus.sql
START TRANSACTION;

-- Children's Menu
INSERT INTO `restaurant_menus` (`id`, `locationId`, `title`, `slug`, `description`, `timings`, `imageUrl`, `sortOrder`, `isActive`, `createdAt`, `updatedAt`) VALUES ('cmtsape8000097msc32t1ujzw', 'carambola-main', 'Children''s Menu', 'childrens-menu', NULL, NULL, NULL, 1, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`), `timings`=VALUES(`timings`), `imageUrl`=VALUES(`imageUrl`), `sortOrder`=VALUES(`sortOrder`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW();
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsci58b001b3a9z2dl1gsvm', 'cmtsape8000097msc32t1ujzw', 'Kid''s Selection', 'Entrees', 0) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001c3a9z3ipklv5l', 'cmtsci58b001b3a9z2dl1gsvm', 'Mozzarella Sticks', 'Crispy mozzarella sticks with marinara sauce.', 10, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001d3a9zihi6rujp', 'cmtsci58b001b3a9z2dl1gsvm', 'Chicken Tenders', 'Breaded and baked, served with ketchup or honey mustard.', 13, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001e3a9z3slum8ci', 'cmtsci58b001b3a9z2dl1gsvm', 'Gourmet Mac and Cheese', 'Made with aged cheddar and a hint of truffle oil.', 15, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001f3a9z12jtt438', 'cmtsci58b001b3a9z2dl1gsvm', 'Grilled Cheese Sandwich', 'Melted American cheese between slices of buttery grilled bread.', 12, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001g3a9z30x41vj4', 'cmtsci58b001b3a9z2dl1gsvm', 'Kids'' Portion Pasta with Butter or Marinara', 'Choice of plain pasta with melted butter or marinara sauce.', 13, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001h3a9znhmg2pz7', 'cmtsci58b001b3a9z2dl1gsvm', 'Homemade Mini Cheese Pizza', 'Add pepperoni +$3, add vegetables +$2.', 13, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsci58b001i3a9zfjd89qjr', 'cmtsape8000097msc32t1ujzw', 'Accompaniments', NULL, 1) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001j3a9zdiym6jys', 'cmtsci58b001i3a9zfjd89qjr', 'French Fries', 'Golden and perfectly crispy.', 7, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsci58b001k3a9z304ag2yi', 'cmtsci58b001i3a9zfjd89qjr', 'Garlic Bread Sticks', 'Soft, freshly baked garlic bread sticks served with marinara sauce.', 5, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);

-- Lunch Menu
INSERT INTO `restaurant_menus` (`id`, `locationId`, `title`, `slug`, `description`, `timings`, `imageUrl`, `sortOrder`, `isActive`, `createdAt`, `updatedAt`) VALUES ('cmtsapeaw000c7msc1evqybt8', 'carambola-main', 'Lunch Menu', 'lunch-menu', NULL, NULL, NULL, 2, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`), `timings`=VALUES(`timings`), `imageUrl`=VALUES(`imageUrl`), `sortOrder`=VALUES(`sortOrder`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW();
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga8400013a9zdi7kv2cd', 'cmtsapeaw000c7msc1evqybt8', 'Soups and Salads', NULL, 0) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500023a9zt6ue49qy', 'cmtscga8400013a9zdi7kv2cd', 'Soup of the Day', 'Our chef''s selection.', 12.3, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500033a9zdyvtjs7t', 'cmtscga8400013a9zdi7kv2cd', 'Kittitian Mixed Green Salad', 'Fresh greens with tomatoes, cucumbers and bell peppers. Add chicken $3, shrimp $5.', 16.39, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500043a9z1isyg4nj', 'cmtscga8400013a9zdi7kv2cd', 'Watermelon and Feta Salad', 'Feta cheese and watermelon with balsamic reduction.', 18.03, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga8500053a9zkj7etwbp', 'cmtsapeaw000c7msc1evqybt8', 'Entrees', 'Served with rice and peas, French fries, or fried plantain', 1) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500063a9zcep5xbqk', 'cmtscga8500053a9zkj7etwbp', 'Grilled Caribbean Spiny Lobster Tail', 'Half or whole tail with garlic butter. Market price.', NULL, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500073a9zedzv870m', 'cmtscga8500053a9zkj7etwbp', 'Catch of the Day', 'Chef''s selection, prepared fried, steamed, grilled or roasted.', 35.25, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500083a9z9ciwbr36', 'cmtscga8500053a9zkj7etwbp', 'Fish Fingers', 'Breaded and baked with dipping sauce.', 13.11, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8500093a9zodswxgk0', 'cmtscga8500053a9zkj7etwbp', 'Chicken Wings', 'Six wings in rum-passion, BBQ, mango-lime, jerk, or spicy sauce.', 22.13, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000a3a9zo66ep383', 'cmtscga8500053a9zkj7etwbp', 'Popcorn Chicken', 'Double-breaded crispy chicken with ranch dip.', 19.67, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000b3a9z659x4j3c', 'cmtscga8500053a9zkj7etwbp', 'Char-Grilled BBQ Chicken', 'Leg quarter with rum-flavored BBQ sauce.', 23.77, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000c3a9zfpy3fn46', 'cmtscga8500053a9zkj7etwbp', 'Caribbean Style Jerked Chicken', 'Leg quarter in secret blend spice, grilled.', 23.77, 6) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000d3a9zq64wa1r6', 'cmtscga8500053a9zkj7etwbp', 'BBQ Baby Back Ribs', 'House-rubbed and whiskey-infused sauce.', 27.05, 7) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000e3a9zr3bctfuo', 'cmtscga8500053a9zkj7etwbp', 'Kittitian Flavour', 'Chef''s special local St. Kitts dish.', 19.67, 8) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga85000f3a9zbgik47j9', 'cmtsapeaw000c7msc1evqybt8', 'Pastas', 'Choice of Alfredo or tomato sauce', 2) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000g3a9zedesofy1', 'cmtscga85000f3a9zbgik47j9', 'Vegetable', NULL, 25.41, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000h3a9zab031eke', 'cmtscga85000f3a9zbgik47j9', 'Chicken', NULL, 27.05, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000i3a9zfjm649ai', 'cmtscga85000f3a9zbgik47j9', 'Seafood', NULL, 31.97, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga85000j3a9z0tb2ienc', 'cmtsapeaw000c7msc1evqybt8', 'Sandwiches and Burgers', 'Served with rice and peas, French fries, or fried plantain', 3) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000k3a9zbbfg5be1', 'cmtscga85000j3a9z0tb2ienc', 'Caribbean Spiny Lobster Sandwich', 'Sauteed lobster with vegetables and spicy Marie Rose sauce.', 35.25, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000l3a9zbh8td55v', 'cmtscga85000j3a9z0tb2ienc', 'Jerk Chicken Wrap', 'Chicken, vegetables, cheese with mango chutney.', 25.41, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga85000m3a9zz3q7clyk', 'cmtscga85000j3a9z0tb2ienc', 'Club Sandwich', 'Grilled chicken, bacon, lettuce, tomato, mayo.', 22.95, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000n3a9zdijvbht8', 'cmtscga85000j3a9z0tb2ienc', 'Grilled Vegetable Wrap', 'With balsamic and olive oil dressing.', 22.13, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000o3a9zcrepji8p', 'cmtscga85000j3a9z0tb2ienc', 'Traditional Beef Burger', '8oz patty with tomato, lettuce, pickles.', 22.13, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000p3a9zqghdoy2h', 'cmtscga85000j3a9z0tb2ienc', 'Fish Burger', 'Breaded grouper with tomato, lettuce, pickles.', 25.41, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000q3a9zy2lcvedg', 'cmtscga85000j3a9z0tb2ienc', 'Fried Chicken Burger', 'With optional spicy mayo. Add cheese $1.64, bacon $2.46.', 27.05, 6) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga86000r3a9zqwdm0h5v', 'cmtsapeaw000c7msc1evqybt8', 'Pizzas', NULL, 4) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000s3a9ziz3t4nxs', 'cmtscga86000r3a9zqwdm0h5v', 'Cheese', NULL, 19.67, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000t3a9zhtza5yu4', 'cmtscga86000r3a9zqwdm0h5v', 'Pepperoni', NULL, 22.13, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000u3a9zr3ztgqei', 'cmtscga86000r3a9zqwdm0h5v', 'Vegetarian', NULL, 23.77, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000v3a9zhjvlsojj', 'cmtscga86000r3a9zqwdm0h5v', 'Meat Lovers', NULL, 25.41, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000w3a9zwdimngkp', 'cmtscga86000r3a9zqwdm0h5v', 'Seafood', NULL, 27.05, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000x3a9z5pr2414x', 'cmtscga86000r3a9zqwdm0h5v', 'Jerked Lobster', NULL, 35.25, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000y3a9zpowolynv', 'cmtscga86000r3a9zqwdm0h5v', 'Hawaiian', NULL, 23.77, 6) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga86000z3a9z4suxlg5x', 'cmtscga86000r3a9zqwdm0h5v', 'Kittitian Saltfish', NULL, 22.95, 7) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga8600103a9zzaod5xdw', 'cmtsapeaw000c7msc1evqybt8', 'Kids Selection', NULL, 5) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600113a9zshync63z', 'cmtscga8600103a9zzaod5xdw', 'Mini Cheese Pizza', NULL, 13.11, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600123a9zqv3066bg', 'cmtscga8600103a9zzaod5xdw', 'Baked Mac and Cheese', NULL, 14.75, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600133a9zvo14phnn', 'cmtscga8600103a9zzaod5xdw', 'Grilled Cheese Sandwich', NULL, 12.3, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600143a9zhzp541zt', 'cmtscga8600103a9zzaod5xdw', 'Chicken Tenders and Fries', NULL, 13.11, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600153a9zcrct1r70', 'cmtscga8600103a9zzaod5xdw', 'Fish Fingers and Fries', NULL, 13.11, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscga8600163a9z8c89g15h', 'cmtsapeaw000c7msc1evqybt8', 'Dessert Pizzas', NULL, 6) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600173a9zslgyfaex', 'cmtscga8600163a9z8c89g15h', 'Peach Pizza', 'Peach with Bavarian cream, cinnamon sugar, icing drizzle.', 13.93, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscga8600183a9z538ywbh2', 'cmtscga8600163a9z8c89g15h', 'Nutella Pizza', 'Hazelnut spread and caramelized bananas.', 12.3, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);

-- Dinner Menu
INSERT INTO `restaurant_menus` (`id`, `locationId`, `title`, `slug`, `description`, `timings`, `imageUrl`, `sortOrder`, `isActive`, `createdAt`, `updatedAt`) VALUES ('cmtsapef5000f7mscq2ckojdw', 'carambola-main', 'Dinner Menu', 'dinner-menu', 'An elegant evening of Caribbean-inspired fine dining, from fresh-caught seafood to indulgent desserts.', '6:00 PM - 10:00 PM', NULL, 3, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`), `timings`=VALUES(`timings`), `imageUrl`=VALUES(`imageUrl`), `sortOrder`=VALUES(`sortOrder`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW();
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8k000wy0pvn4w9qjk3', 'cmtsapef5000f7mscq2ckojdw', 'Soups', 'Appetizers', 0) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l000xy0pvpxoa0qng', 'cmtsbkx8k000wy0pvn4w9qjk3', 'Roasted Pumpkin Soup', 'Local pumpkin with cinnamon cream.', 13, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l000yy0pvreuwfh2p', 'cmtsbkx8k000wy0pvn4w9qjk3', 'Soup of Now', 'Chef''s nightly selection.', 15, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l000zy0pvcthvdnah', 'cmtsapef5000f7mscq2ckojdw', 'Cold Appetizers', 'Appetizers', 1) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0010y0pv29ms71hy', 'cmtsbkx8l000zy0pvcthvdnah', 'Caprese Salad', 'Fresh buffalo mozzarella, heirloom tomatoes, basil, balsamic and olive oil.', 19, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0011y0pve7k897kz', 'cmtsbkx8l000zy0pvcthvdnah', 'Roasted Beet and Goat Cheese Salad', 'Served with micro herbs and balsamic reduction.', 20, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0012y0pveawp2qen', 'cmtsbkx8l000zy0pvcthvdnah', 'Caesar Salad with Grilled Chicken', 'Tender romaine hearts with house-made Caesar dressing.', 23, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0013y0pvlxoaawtf', 'cmtsbkx8l000zy0pvcthvdnah', 'Caesar Salad with Grilled Shrimp', 'Tender romaine hearts with house-made Caesar dressing.', 25, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l0014y0pvc6khjxm5', 'cmtsapef5000f7mscq2ckojdw', 'Hot Appetizers', 'Appetizers', 2) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0015y0pv2d9me320', 'cmtsbkx8l0014y0pvc6khjxm5', 'Butternut Squash and Mushroom Ravioli', 'Open ravioli topped with roasted butternut squash, sauteed mushrooms, scallions and onions.', 20, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0016y0pvgbq192bl', 'cmtsbkx8l0014y0pvc6khjxm5', 'Pan Seared Scallops', 'Served with clarified butter and ginger.', 23, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0017y0pv7hos0b1t', 'cmtsbkx8l0014y0pvc6khjxm5', 'Kittitian Conch Fritters', 'Locally caught conch tenderized with herbs and spices, served with lemon mayonnaise.', 25, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0018y0pv38l7bdpt', 'cmtsbkx8l0014y0pvc6khjxm5', 'Fried Calamari', 'Lightly battered and deep-fried squid, served with lemon and sambuca marinara sauce.', 32, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l0019y0pv3morgqvl', 'cmtsbkx8l0014y0pvc6khjxm5', 'Grilled Shrimp', 'Served with vegetable ratatouille and drizzled with fresh lemon juice.', 23, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001ay0pvaqesj919', 'cmtsbkx8l0014y0pvc6khjxm5', 'Carambola Coquille', 'Classic French seafood delicacy featuring tender scallops, fish and lobster in a rich, creamy sauce.', 32, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l001by0pvzhnqseji', 'cmtsapef5000f7mscq2ckojdw', 'Land', 'Entrees', 3) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001cy0pvjn9yklza', 'cmtsbkx8l001by0pvzhnqseji', 'Chicken Cordon Bleu', 'Crispy chicken breast breaded and stuffed with ham and Swiss cheese in Dijon cream sauce.', 32, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001dy0pvl4rusxp8', 'cmtsbkx8l001by0pvzhnqseji', 'Beef Tenderloin', 'Marinated to perfection and served with red wine and blueberry reduction.', 24, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001ey0pvvqd5uuzp', 'cmtsbkx8l001by0pvzhnqseji', 'Grilled Rack of Lamb', 'Served with rosemary and mint reduction.', 53, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001fy0pvwxayfym2', 'cmtsbkx8l001by0pvzhnqseji', 'Steak Diane', 'Pan-seared steak served with Diane sauce — mushrooms, brandy, cream and Dijon mustard.', 44, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001gy0pv6iwsjs0i', 'cmtsbkx8l001by0pvzhnqseji', 'Pineapple and Star Anise Braised Boneless Baby Back Ribs', 'Served with pineapple chutney.', 32, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001hy0pv3izwr1h5', 'cmtsbkx8l001by0pvzhnqseji', 'Classic Beef Burger', '8oz beef patty on a toasted bun, pickles, tomatoes.', 24, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l001iy0pv068anuxu', 'cmtsapef5000f7mscq2ckojdw', 'Sea', 'Entrees', 4) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001jy0pverqy69i2', 'cmtsbkx8l001iy0pv068anuxu', 'Grilled Herb Red Snapper', 'Fillet of snapper with onions, scallions and garlic, with creamy caper sauce.', 42, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001ky0pv87yiey73', 'cmtsbkx8l001iy0pv068anuxu', 'Mahi-Mahi', 'Fresh catch, prepared your way — grilled, pan fried, steamed or roasted.', 41, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001ly0pvbtui9bvt', 'cmtsbkx8l001iy0pv068anuxu', 'Scottish Salmon', 'Prepared your way — grilled, pan fried or poached.', 40, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001my0pvsdvyzcep', 'cmtsbkx8l001iy0pv068anuxu', 'Grilled Caribbean Spiny Lobster Tail', 'Stuffed with seasoned crab meat, served with garlic butter.', 57, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001ny0pvoxulrrs5', 'cmtsbkx8l001iy0pv068anuxu', 'Pan Seared Sea Bass', 'Sea bass fillet pan seared and served with herb-infused cream sauce.', 57, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l001oy0pv9dqm4tut', 'cmtsapef5000f7mscq2ckojdw', 'Surf and Turf', 'Entrees', 5) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001py0pvpakdfhz6', 'cmtsbkx8l001oy0pv9dqm4tut', 'Caribbean Spiny Lobster Tail with Rack of Lamb or Beef Tenderloin', 'A harmonious blend of succulent seafood and tender meat.', 63, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l001qy0pv6x6ahn6d', 'cmtsapef5000f7mscq2ckojdw', 'Vegan', 'Entrees', 6) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001ry0pvear4bs32', 'cmtsbkx8l001qy0pv6x6ahn6d', 'Pumpkin Pasta', 'Linguine pasta with spinach and fresh herbs, tossed in creamy coconut pumpkin sauce.', 23, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001sy0pv5ryr1eip', 'cmtsbkx8l001qy0pv6x6ahn6d', 'Quinoa with Roasted Vegetables', 'Quinoa with seasonal roasted vegetables.', 32, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtsbkx8l001ty0pvl2kcrirt', 'cmtsapef5000f7mscq2ckojdw', 'Pasta', 'Entrees', 7) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001uy0pvr8wvvcn1', 'cmtsbkx8l001ty0pvl2kcrirt', 'Creamy Chicken Alfredo', 'Fettuccine tossed in rich Alfredo sauce with grilled chicken, Parmesan cheese and fresh parsley.', 25, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001vy0pvc2i7ulpk', 'cmtsbkx8l001ty0pvl2kcrirt', 'Garlic Butter Shrimp Scampi', 'Linguine with succulent shrimp, garlic, cherry tomatoes and fresh herbs in white wine and butter sauce.', 31, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtsbkx8l001wy0pvvoc5fzmt', 'cmtsbkx8l001ty0pvl2kcrirt', 'Seafood Linguini', 'Sauteed fish, calamari and shrimp tossed with olives, capers and scallions, served with linguini.', 50, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);

-- Seasonal Specials
INSERT INTO `restaurant_menus` (`id`, `locationId`, `title`, `slug`, `description`, `timings`, `imageUrl`, `sortOrder`, `isActive`, `createdAt`, `updatedAt`) VALUES ('cmtscjax8001n3a9zd6nvn87a', 'carambola-main', 'Seasonal Specials', 'seasonal-specials', NULL, NULL, NULL, 4, 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `description`=VALUES(`description`), `timings`=VALUES(`timings`), `imageUrl`=VALUES(`imageUrl`), `sortOrder`=VALUES(`sortOrder`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW();
INSERT INTO `restaurant_menu_sections` (`id`, `menuId`, `heading`, `subheading`, `sortOrder`) VALUES ('cmtscjax8001o3a9ztrxhln7k', 'cmtscjax8001n3a9zd6nvn87a', 'Chef Recommended', NULL, 0) ON DUPLICATE KEY UPDATE `heading`=VALUES(`heading`), `subheading`=VALUES(`subheading`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001p3a9ze84nob1u', 'cmtscjax8001o3a9ztrxhln7k', 'Roasted Beef and Goat Cheese Salad', 'Served with micro herbs and balsamic reduction.', 19, 0) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001q3a9z3fgbnuku', 'cmtscjax8001o3a9ztrxhln7k', 'Sauteed Escargot', 'With garlic, mushrooms and green grapes, finished with parsley oil.', 16, 1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001r3a9zdi9aaqnc', 'cmtscjax8001o3a9ztrxhln7k', 'Pan Seared Scallops', 'Served with clarified butter and ginger.', 18, 2) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001s3a9z3kpvi8h2', 'cmtscjax8001o3a9ztrxhln7k', 'Yam and Lobster Thermidor', 'Caribbean spiny lobster baked in a mushroom cream sauce and topped with Parmesan cheese.', 44, 3) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001t3a9zbtyrzhvf', 'cmtscjax8001o3a9ztrxhln7k', 'Mahi-Mahi, Prepared Your Way', 'Fresh catch, prepared your way — grilled, pan fried, steamed or roasted.', 32, 4) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001u3a9zyas6o7nv', 'cmtscjax8001o3a9ztrxhln7k', 'Pan Seared Seabass', 'Sea bass fillet pan seared and served with herb-infused cream sauce.', 48, 5) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001v3a9z6vs9h3u3', 'cmtscjax8001o3a9ztrxhln7k', 'Scottish Salmon', 'Prepared your way — grilled, pan fried or poached.', 35, 6) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001w3a9zjemlmod5', 'cmtscjax8001o3a9ztrxhln7k', 'Beef Tenderloin', 'Marinated to perfection and served with a red wine and blueberry reduction.', 40, 7) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001x3a9z6i93yusy', 'cmtscjax8001o3a9ztrxhln7k', 'Creamy Chicken Alfredo', 'Fettuccine pasta tossed in a rich Alfredo sauce with grilled chicken, Parmesan cheese and fresh parsley.', 20, 8) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001y3a9zodm9ok4b', 'cmtscjax8001o3a9ztrxhln7k', 'Pineapple and Star Anise Baby Back Ribs', 'Served with pineapple chutney.', 25, 9) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax8001z3a9zqqvffeq9', 'cmtscjax8001o3a9ztrxhln7k', 'Char-Grilled Breast of Chicken', 'With Caribbean curry sauce and root vegetables.', 28, 10) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);
INSERT INTO `restaurant_menu_items` (`id`, `sectionId`, `name`, `description`, `price`, `sortOrder`) VALUES ('cmtscjax800203a9z41wnbjcr', 'cmtscjax8001o3a9ztrxhln7k', 'Steak Diane', 'Pan-seared steak served with Diane sauce — mushrooms, brandy, cream and Dijon mustard.', 35, 11) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `price`=VALUES(`price`), `sortOrder`=VALUES(`sortOrder`);

COMMIT;
