-- Bring the hosted catalogue in line with local.
--
-- GENERATED by prisma/generate-catalogue-sync.js on 2026-10-09.
-- Don't hand-edit this file — change the local database and re-run the
-- generator, so local stays the single source of truth.
--
--   mysql -u USER -p --default-character-set=utf8mb4 DBNAME < sync-catalogue-to-live.sql
--
-- The --default-character-set=utf8mb4 is required, or the accented
-- characters in the descriptions are mangled on import.
--
-- Rows are matched on each table's own unique key (excursions.slug,
-- rental_items.slug, rental_spots(item, code), rental_time_slots(item, label))
-- and never on id, so a row that already exists on the host is updated in
-- place and keeps the id its existing bookings point at. The location is
-- resolved at run time, because the hosted location id differs from local.
--
-- Nothing here deletes a catalogue item: one that exists on the host but
-- not locally is left in place rather than dropped, because it may have
-- bookings against it. Retire those from the admin panel instead.
--
-- Departure times are the one exception — they are replaced per excursion,
-- which is safe because bookings reference the excursion, not the
-- departure_times row. Rental spots and time slots that exist on the host
-- but not locally are deactivated rather than deleted, so they stop being
-- bookable without breaking the bookings already attached to them.
--
-- Bookings, orders, locations, settings and admin users are untouched.

SET NAMES utf8mb4;

START TRANSACTION;

-- The host's location row (local 'coccolobo-main' vs live 'carambola-main'),
-- resolved by age rather than by a hardcoded id.
SET @loc = (SELECT id FROM locations ORDER BY createdAt LIMIT 1);

-- ===================== Excursions =====================

-- Coccolobo All Inclusive Cabana
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9uq000r76ahuxsx34ly', @loc, 'Coccolobo All Inclusive Cabana', 'coccolobo-all-inclusive-cabana', 'The full cabana experience for up to four guests, adding a lunch menu with enhanced offerings on top of the open bar and dedicated server. Flat rate for up to four guests.', 'Day VIP passes for up to four guests, private shaded space, open bar, cabana lunch menu with enhanced offerings, dedicated server', 'Food and drinks outside package sold separately', 360, 'Coccolobo Beach Club', NULL, '', '[]', '560', '0', 4, 0, '21:00', 'ACTIVE', 'FLAT_RATE', '/uploads/images/97bd1bdb-9473-4189-ae0a-bbbf1320eb2d.jpg', '/uploads/images/effe97e6-aede-4344-9846-7be60090be29.jpg', 1)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'coccolobo-all-inclusive-cabana');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtluiqbj000b2qtnjm68md5i', p.id, '10:00', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'coccolobo-all-inclusive-cabana';

-- Coccolobo Cabana
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9ul000o76ahbqf8nq1y', @loc, 'Coccolobo Cabana', 'coccolobo-cabana', 'A private shaded cabana with premium comfort for up to four guests, with a dedicated server and open bar. Flat rate for up to four guests.', 'Day VIP passes for up to four guests, private shaded space, open bar (Johnnie Walker Black, Absolut Vodka, Beefeater Gin, Mount Gay Rum, local beers, house wines, rum punch, sodas, juices, bottled water), dedicated server', 'Food and drinks outside package sold separately', 360, 'Coccolobo Beach Club', NULL, '', '[]', '400', '0', 4, 0, '21:00', 'ACTIVE', 'FLAT_RATE', '/uploads/images/b32302c1-96c2-4d80-a0cd-4209d7a6ca0e.jpg', '/uploads/images/fb91697c-1b3f-4356-b2dd-0a37fffb701d.jpg', 1)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'coccolobo-cabana');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtlu519i00052qtnho0szazc', p.id, '10:00', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'coccolobo-cabana';

-- Coccolobo VIP Experience
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9uf000l76ahiwnyhi3e', @loc, 'Coccolobo VIP Experience', 'coccolobo-vip-experience', 'A luxury beach experience with a dedicated server attending to all your needs, an open bar, and a flexible start time.', 'Open bar (Johnnie Walker Black, Absolut Vodka, Beefeater Gin, Mount Gay Rum, local beers, red and white house wines, rum punch, sodas, juices, bottled water), beach chair, umbrella, facility amenities, Wi-Fi access, dedicated server', 'Food and drinks outside package sold separately', 210, 'Coccolobo Beach Club', NULL, '', '[]', '100', '0', 80, 0, '21:00', 'ACTIVE', 'PER_GUEST', '/uploads/images/ec911e67-d81e-408b-8b3f-1da1bd020cbb.jpg', '/uploads/images/9c0d70f5-28c1-4bfd-999c-ace1dc43103b.jpg', 6)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'coccolobo-vip-experience');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtlu5afi00082qtnsjdp8low', p.id, '10:00', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'coccolobo-vip-experience';

-- Day Pass to Coccolobo Beach Club
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9tl000976ah54xfbez8', @loc, 'Day Pass to Coccolobo Beach Club', 'day-pass', 'Spend the day relaxing at Coccolobo Beach Club with your own beach chair and umbrella, full access to our facilities, Wi-Fi, towel service and a welcome rum punch.', 'Beach chair, umbrella, facility amenities, Wi-Fi access, towel, welcome rum punch', 'Food and drinks sold separately', 360, 'Coccolobo Beach Club', NULL, NULL, '[]', '45', NULL, 50, 0, '21:00', 'ACTIVE', 'PER_GUEST', '', '', 1)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'day-pass');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtcig9tl000a76ahggskoxy7', p.id, '10:00', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'day-pass';

-- Foodie & Beach
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9tv000c76ahvqp5f6mp', @loc, 'Foodie & Beach', 'foodie-and-beach', 'Discover the flavours of St. Kitts with a tasting of authentic Kittitian favourites including Goat Water, Cook-Up, Saltfish & Dumplings and Steamed Fish with Turn Corn. Finish with local desserts and refreshments, and take home a recipe card to recreate a little taste of St. Kitts.', 'Tasting portions of local dishes, chair, umbrella, facility amenities, Wi-Fi access', 'Food and drinks outside package sold separately', 240, 'Coccolobo Beach Club', NULL, NULL, '[]', '75', NULL, 40, 0, '21:00', 'ACTIVE', 'PER_GUEST', NULL, NULL, 4)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'foodie-and-beach');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtcig9tv000d76ah9m6rbbv3', p.id, '11:30', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'foodie-and-beach';

-- Sushi Class 101 Beach Break
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9u1000f76ah80kcqyxy', @loc, 'Sushi Class 101 Beach Break', 'sushi-class-101-beach-break', 'Learn the art of sushi making with guidance from our sushi chef as you create your own eight-piece sushi roll. Afterwards, unwind with two hours of beach time at Coccolobo Beach Club.', 'Beach chair, umbrella, facility amenities, Wi-Fi access, one glass of sake, one glass of house wine, one sushi roll', 'Food and drinks sold separately', 210, 'Coccolobo Beach Club', NULL, NULL, '[]', '75', NULL, 40, 0, '21:00', 'ACTIVE', 'PER_GUEST', NULL, NULL, 4)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'sushi-class-101-beach-break');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtcig9u1000g76ah9xqayvls', p.id, '10:00', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'sushi-class-101-beach-break';

-- Wine Tasting & Beach
INSERT INTO excursions (id, locationId, title, slug, description, included, excluded, durationMinutes, meetingPoint, mapUrl, whatToBring, images, priceAdult, priceChild, capacityDefault, cutoffHoursBefore, cutoffTime, status, pricingType, cardImageUrl, headerImageUrl, minGuests)
VALUES ('cmtcig9u8000i76ahx54sfdu9', @loc, 'Wine Tasting & Beach', 'wine-tasting-and-beach', 'Sip, savour and unwind by the Caribbean Sea with a curated tasting of wines from Opus Fine Wine & Spirits. Enjoy your tasting in our relaxed beachfront setting, followed by time to soak up the atmosphere at Coccolobo Beach Club.', 'Beach chair, umbrella, facility amenities, Wi-Fi access, 3 glasses of wine (red, white, rosé), hors d''oeuvres, cheese platter', 'Food and drinks sold separately', 210, 'Coccolobo Beach Club', NULL, NULL, '[]', '80', NULL, 40, 0, '21:00', 'ACTIVE', 'PER_GUEST', NULL, NULL, 4)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), title = VALUES(title), description = VALUES(description), included = VALUES(included), excluded = VALUES(excluded), durationMinutes = VALUES(durationMinutes), meetingPoint = VALUES(meetingPoint), mapUrl = VALUES(mapUrl), whatToBring = VALUES(whatToBring), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), capacityDefault = VALUES(capacityDefault), cutoffHoursBefore = VALUES(cutoffHoursBefore), cutoffTime = VALUES(cutoffTime), status = VALUES(status), pricingType = VALUES(pricingType), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl), minGuests = VALUES(minGuests);
DELETE FROM departure_times WHERE excursionId = (SELECT id FROM excursions WHERE slug = 'wine-tasting-and-beach');
INSERT INTO departure_times (id, excursionId, time, daysOfWeek, isActive)
SELECT 'cmtcig9u9000j76ahkqvtless', p.id, '11:30', '[0,1,2,3,4,5,6]', 1 FROM excursions p WHERE p.slug = 'wine-tasting-and-beach';

-- ===================== Rental items =====================

-- Beach Chair
INSERT INTO rental_items (id, locationId, name, slug, description, images, priceAdult, priceChild, status, durationMinutes, cardImageUrl, headerImageUrl)
VALUES ('cmtch3gmy000c3dscihfm8p1c', @loc, 'Beach Chair', 'beach-chair', 'Find your perfect spot on the sand with a reserved beach chair at Coccolobo Beach Club. Stretch out, soak up the Caribbean sunshine, and enjoy beautiful ocean views in a relaxed tropical setting. Take a refreshing dip in the sea, grab a drink from our beachside bar, or simply sit back and enjoy island life at your own pace.', NULL, '15', '0', 'ACTIVE', 240, '/uploads/images/948def5c-7ded-46bb-8424-842e22904472.jpg', '/uploads/images/3207abe4-8d4a-49a5-8562-edaca037033b.jpg')
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), name = VALUES(name), description = VALUES(description), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), status = VALUES(status), durationMinutes = VALUES(durationMinutes), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl);
INSERT INTO rental_spots (id, rentalItemId, code, isActive, quantity)
SELECT 'cmtgpw81j000wbvuusaxvlpqd', p.id, 'Row A', 1, 5 FROM rental_items p WHERE p.slug = 'beach-chair'
ON DUPLICATE KEY UPDATE isActive = VALUES(isActive), quantity = VALUES(quantity);
INSERT INTO rental_spots (id, rentalItemId, code, isActive, quantity)
SELECT 'cmtgpw81z000ybvuu4xk169x3', p.id, 'Row B', 1, 5 FROM rental_items p WHERE p.slug = 'beach-chair'
ON DUPLICATE KEY UPDATE isActive = VALUES(isActive), quantity = VALUES(quantity);
INSERT INTO rental_time_slots (id, rentalItemId, label, startTime, endTime, isActive)
SELECT 'cmtgpw82b0010bvuuoocsty2k', p.id, '9:00 AM - 1:00 PM', '09:00', '13:00', 1 FROM rental_items p WHERE p.slug = 'beach-chair'
ON DUPLICATE KEY UPDATE startTime = VALUES(startTime), endTime = VALUES(endTime), isActive = VALUES(isActive);
INSERT INTO rental_time_slots (id, rentalItemId, label, startTime, endTime, isActive)
SELECT 'cmtgpw82k0012bvuutljx1xi8', p.id, '1:00 PM - 5:00 PM', '13:00', '17:00', 1 FROM rental_items p WHERE p.slug = 'beach-chair'
ON DUPLICATE KEY UPDATE startTime = VALUES(startTime), endTime = VALUES(endTime), isActive = VALUES(isActive);
UPDATE rental_spots SET isActive = 0 WHERE rentalItemId = (SELECT id FROM rental_items WHERE slug = 'beach-chair')
  AND code NOT IN ('Row A', 'Row B');
UPDATE rental_time_slots SET isActive = 0 WHERE rentalItemId = (SELECT id FROM rental_items WHERE slug = 'beach-chair')
  AND label NOT IN ('9:00 AM - 1:00 PM', '1:00 PM - 5:00 PM');

-- Beach Day with Lunch at Coco Grill
INSERT INTO rental_items (id, locationId, name, slug, description, images, priceAdult, priceChild, status, durationMinutes, cardImageUrl, headerImageUrl)
VALUES ('coco_rental_beach_lunch', @loc, 'Beach Day with Lunch at Coco Grill', 'beach-day-with-lunch', 'Enjoy the perfect beach day at Coccolobo Beach Club! Relax on your reserved beach chair beneath the shade of an umbrella, soak up the Caribbean sunshine, and take in the beautiful ocean views. When you''re ready to refuel, enjoy a delicious freshly prepared lunch from our beachside grill. Sit back, unwind, and let us take care of the rest while you enjoy a laid-back day in paradise.', NULL, '45', '45', 'ACTIVE', 240, NULL, NULL)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), name = VALUES(name), description = VALUES(description), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), status = VALUES(status), durationMinutes = VALUES(durationMinutes), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl);
INSERT INTO rental_spots (id, rentalItemId, code, isActive, quantity)
SELECT 'coco_lunch_spot_a', p.id, 'Row A', 1, 20 FROM rental_items p WHERE p.slug = 'beach-day-with-lunch'
ON DUPLICATE KEY UPDATE isActive = VALUES(isActive), quantity = VALUES(quantity);
INSERT INTO rental_spots (id, rentalItemId, code, isActive, quantity)
SELECT 'coco_lunch_spot_b', p.id, 'Row B', 1, 20 FROM rental_items p WHERE p.slug = 'beach-day-with-lunch'
ON DUPLICATE KEY UPDATE isActive = VALUES(isActive), quantity = VALUES(quantity);
INSERT INTO rental_time_slots (id, rentalItemId, label, startTime, endTime, isActive)
SELECT 'coco_lunch_slot_am', p.id, '9:00 AM - 1:00 PM', '09:00', '13:00', 1 FROM rental_items p WHERE p.slug = 'beach-day-with-lunch'
ON DUPLICATE KEY UPDATE startTime = VALUES(startTime), endTime = VALUES(endTime), isActive = VALUES(isActive);
INSERT INTO rental_time_slots (id, rentalItemId, label, startTime, endTime, isActive)
SELECT 'coco_lunch_slot_pm', p.id, '1:00 PM - 5:00 PM', '13:00', '17:00', 1 FROM rental_items p WHERE p.slug = 'beach-day-with-lunch'
ON DUPLICATE KEY UPDATE startTime = VALUES(startTime), endTime = VALUES(endTime), isActive = VALUES(isActive);
UPDATE rental_spots SET isActive = 0 WHERE rentalItemId = (SELECT id FROM rental_items WHERE slug = 'beach-day-with-lunch')
  AND code NOT IN ('Row A', 'Row B');
UPDATE rental_time_slots SET isActive = 0 WHERE rentalItemId = (SELECT id FROM rental_items WHERE slug = 'beach-day-with-lunch')
  AND label NOT IN ('9:00 AM - 1:00 PM', '1:00 PM - 5:00 PM');

-- Beach Umbrellas & Chairs
INSERT INTO rental_items (id, locationId, name, slug, description, images, priceAdult, priceChild, status, durationMinutes, cardImageUrl, headerImageUrl)
VALUES ('cmu2vpjtk0001cur7c14qapox', @loc, 'Beach Umbrellas & Chairs', 'beach-umbrellas-chairs', 'Relax and unwind at Coccolobo Beach Club with your own reserved beach chair and umbrella. Soak up the Caribbean sunshine, enjoy the refreshing sea breeze, and take in the stunning turquoise ocean views. Whether you''re swimming, sunbathing, or simply enjoying the laid-back island atmosphere, it''s the perfect way to spend your day in paradise.', '["/uploads/images/67687bf8-1476-4c7e-b5db-777fc9c7a0b5.jpg","/uploads/images/92f71da2-3d8f-4963-ad6d-4f2fa28b53db.jpg","/uploads/images/5ea8e887-214c-4e26-b285-5fc6bf34f8ff.jpg","/uploads/images/767f9831-9bd6-468f-9e2b-6a84a229d0e3.jpg"]', '50', '50', 'ACTIVE', 240, NULL, NULL)
ON DUPLICATE KEY UPDATE locationId = VALUES(locationId), name = VALUES(name), description = VALUES(description), images = VALUES(images), priceAdult = VALUES(priceAdult), priceChild = VALUES(priceChild), status = VALUES(status), durationMinutes = VALUES(durationMinutes), cardImageUrl = VALUES(cardImageUrl), headerImageUrl = VALUES(headerImageUrl);
INSERT INTO rental_spots (id, rentalItemId, code, isActive, quantity)
SELECT 'cmu2vpx920004cur7rqmoz1lu', p.id, 'Row A', 1, 20 FROM rental_items p WHERE p.slug = 'beach-umbrellas-chairs'
ON DUPLICATE KEY UPDATE isActive = VALUES(isActive), quantity = VALUES(quantity);
INSERT INTO rental_spots (id, rentalItemId, code, isActive, quantity)
SELECT 'cmu2vq4520007cur7103q6ll0', p.id, 'Row B', 1, 20 FROM rental_items p WHERE p.slug = 'beach-umbrellas-chairs'
ON DUPLICATE KEY UPDATE isActive = VALUES(isActive), quantity = VALUES(quantity);
INSERT INTO rental_time_slots (id, rentalItemId, label, startTime, endTime, isActive)
SELECT 'cmu2vqceh000acur7ti3q726a', p.id, '9:00 AM - 1:00 PM', '09:00', '13:00', 1 FROM rental_items p WHERE p.slug = 'beach-umbrellas-chairs'
ON DUPLICATE KEY UPDATE startTime = VALUES(startTime), endTime = VALUES(endTime), isActive = VALUES(isActive);
INSERT INTO rental_time_slots (id, rentalItemId, label, startTime, endTime, isActive)
SELECT 'cmu2vqces000ccur7fwa0adeo', p.id, '1:00 PM - 5:00 PM', '13:00', '17:00', 1 FROM rental_items p WHERE p.slug = 'beach-umbrellas-chairs'
ON DUPLICATE KEY UPDATE startTime = VALUES(startTime), endTime = VALUES(endTime), isActive = VALUES(isActive);
UPDATE rental_spots SET isActive = 0 WHERE rentalItemId = (SELECT id FROM rental_items WHERE slug = 'beach-umbrellas-chairs')
  AND code NOT IN ('Row A', 'Row B');
UPDATE rental_time_slots SET isActive = 0 WHERE rentalItemId = (SELECT id FROM rental_items WHERE slug = 'beach-umbrellas-chairs')
  AND label NOT IN ('9:00 AM - 1:00 PM', '1:00 PM - 5:00 PM');

COMMIT;

-- ===================== Verify =====================
SELECT slug, title, durationMinutes, cutoffTime, minGuests, pricingType, status FROM excursions ORDER BY slug;
SELECT slug, name, durationMinutes, priceAdult, status FROM rental_items ORDER BY slug;
SELECT 'leftover WiFi / persons / Cocolobo' AS check_name,
  (SELECT COUNT(*) FROM excursions WHERE CONCAT_WS(' ', description, included, excluded) REGEXP 'WiFi|persons|Cocolobo Beach')
  + (SELECT COUNT(*) FROM rental_items WHERE description REGEXP 'WiFi|persons|Cocolobo Beach') AS should_be_zero;

-- ===================== Image files =====================
-- These rows reference the files below. Images are stored on disk, not in
-- the database, so copy them to the same paths under the host's uploads
-- folder — otherwise the pages will render broken images.
--   /uploads/images/3207abe4-8d4a-49a5-8562-edaca037033b.jpg
--   /uploads/images/5ea8e887-214c-4e26-b285-5fc6bf34f8ff.jpg
--   /uploads/images/67687bf8-1476-4c7e-b5db-777fc9c7a0b5.jpg
--   /uploads/images/767f9831-9bd6-468f-9e2b-6a84a229d0e3.jpg
--   /uploads/images/92f71da2-3d8f-4963-ad6d-4f2fa28b53db.jpg
--   /uploads/images/948def5c-7ded-46bb-8424-842e22904472.jpg
--   /uploads/images/97bd1bdb-9473-4189-ae0a-bbbf1320eb2d.jpg
--   /uploads/images/9c0d70f5-28c1-4bfd-999c-ace1dc43103b.jpg
--   /uploads/images/b32302c1-96c2-4d80-a0cd-4209d7a6ca0e.jpg
--   /uploads/images/ec911e67-d81e-408b-8b3f-1da1bd020cbb.jpg
--   /uploads/images/effe97e6-aede-4344-9846-7be60090be29.jpg
--   /uploads/images/fb91697c-1b3f-4356-b2dd-0a37fffb701d.jpg
